id: '3e53760d-b9e1-4b9d-dfd5-08dcabe8445a'
version: 'v1.4'
name: 'Demo Github'
description: 'Demo Project for Dimensional MSSQL'
configuration:
  id: 'biGENIUS.Implementation.Generator.Dimensional.Mssql'
  version: '1.6.1'
sourceSystems:
  - id: '2c420864-80c6-48fc-b0f9-3c2398cc0cfc'
    name: 'Blackforest Markets'
    description: ''
    sourceSystemTypeId: 'f69491d8-eed8-43a0-89f9-60195b3415c2'
    activeDiscovery: 'e5854651-06de-44d4-b869-e20cedb601b0'
